version: "3.9"
services:
  dev:
    build: .
    container_name: podcastr_dev
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    ports:
      - 3000:3000
    # command: yarn dev
    stdin_open: true
    tty: true
